### ISSUE TITLE
input files

### ISSUE THREAD

**Issue by ghost** [HajkD/orthologr#2]
I followed the vignette examples and everything worked perfectly. When I tried to use my fasta sequences I have got always the follow error:
"Error in value[[3L]](cond) : File  could not be read properly.
Please make sure that  contains only CDS sequences and is in fasta format."

My files are in the follow format: 

> 001
> ATGCACCATGGCACTGGCCCCCAGAACGTCCAGCATCAGCTGCAGAGGTCCAGGGCCTG
> 002
> CTGGCAGCGAGGGTGAGGAGCAGCCGGCCCACCCCAACCCACCCCCGTCCCCCGCAGCT

Any advice?

sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.2 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] Biostrings_2.38.3   XVector_0.10.0      IRanges_2.4.6       S4Vectors_0.8.7     BiocGenerics_0.16.1 orthologr_0.0.1  
 [7] data.table_1.9.6    seqinr_3.1-3        ade4_1.7-3          dplyr_0.4.3         plyr_1.8.3         

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.3      codetools_0.2-14 foreach_1.4.3    assertthat_0.1   chron_2.3-47     R6_2.1.1         DBI_0.3.1  
 [8] magrittr_1.5     zlibbioc_1.16.0  iterators_1.0.8  tools_3.2.2

**Comment by HajkD** [comment]
Hi marpello,

thank you very much for contacting me. 

I think your file does not fulfill the fasta file format specification. The `>` is missing at the beginning of each header line.

So this format should work:

> \>001
>ATGCACCATGGCACTGGCCCCCAGAACGTCCAGCATCAGCTGCAGAGGTCCAGGGCCTG
> \>002
>CTGGCAGCGAGGGTGAGGAGCAGCCGGCCCACCCCAACCCACCCCCGTCCCCCGCAGCT

Internally my sequence read functions are based on the [Biostrings](https://bioconductor.org/packages/release/bioc/html/Biostrings.html) package.
So you can test whether or not your fasta file is read properly by running:
```r
test <- Biostrings::readDNAStringSet("test.fa")

test
```

Here I assume that your sequences are stored in a fasta file named `test.fa`.
You will see that with your sequence example, the `Biostrings` function returns the following error:

```r
reading FASTA file test.fa: ">" expected at beginning of line 1
```

Please let me know if that was the problem so that I can close this issue.

Cheers,
Hajk

**Comment by marpello** [comment]
Dear Hajk,
sorry for the mistake. My fasta file contains the ">". I did not realised that the ">" in Markdown inserts a blockquote.
With Biostrings I can read my FASTA files.
The question is that I am not able to use the follow command with my sequences:

`hit_tbl <- blast(query_file   = system.file('seqs/ortho_thal_cds.fasta', package = 'orthologr'),                subject_file = system.file('seqs/ortho_lyra_cds_1000.fasta', package = 'orthologr'))`

Can I read my sequences with Biostrings and then use 'blast' command? Or I have to provide a path?

Thank you,
Marco

**Comment by HajkD** [comment]
Dear Marco,

ok thanks for the clarification :)

Unfortunately, the blast command (so far) is not able to take Biostrings objects as input. You
will need to provide the path.

Please let me check where the problem might come from and I will come back to you.

Cheers,
Hajk
