### ISSUE TITLE
Multiple cores

### ISSUE THREAD

**Issue by vinaybaranwal** [HajkD/orthologr#3]
Dear HajkD,
I am trying to perform divergence stratigraphy using orthologr package. The problem I am facing is that it is not using the number of cores I defined using comp_cores. Could you suggest possible reasons and remedies?

PS.lscpu shows 64 CPUs..

Thanks
Vinay

**Comment by HajkD** [comment]
Dear Vinay,

could you please type the following command in the R Console on the machine you are using
to perform divergence_stratigraphy() and post the output?

```r
parallel::detectCores()
```

Depending on the output I will know what the problem might be.

Cheers,
Hajk

**Comment by vinaybaranwal** [comment]
Dear HajkD,

The output I am getting is [1] 64.

**Comment by HajkD** [comment]
Dear Vinay,

thanks for the fast response!
I will have a look at it and come back to you.

Cheers,
Hajk

**Comment by vinaybaranwal** [comment]
Dear Hajk,

For unknown reasons the calculation of DI completes in time. Following are my observations which needs your help in interpreting it. 

Query sequences number = 49000
Subject sequences number = 33164
Result are obtained for 21474 sequences only. 

htop still shows lesser number of threads running, however the job completes.

Does this means that rest of the genes do not have any different?

**Comment by HajkD** [comment]
Dear Vinay,

Yes, your 20K sequences make absolute sense.

For the divergence stratum assignment first orthologous genes
are inferred using BLAST best reciprocal hit.

This means that if you have Species A and Species B,
first BLAST(A,B) is performed and only the best hit for each CDS is retrieved,
second BLAST(B,A) is performed and again only the best hit for each CDS is retrieved.
Only the CDS that have the best hit in both directions BLAST(A,B) = BLAST(B,A) are
considered as orthologs and are used to compute dNdS values.

So since your smaller organism has 34K seqs the maximum possible number of best hits
would already be 34K, but since of course not all CDS are orthologs, this possibility space
will be reduced to much less than 34K. This is why I think that 20K make absolute sense and
reflect my experience when I am computing dNdS values between species.

I hope this helps you to interpret the results.

Thanks for clarifying the threads issue, I also couldn't find any problems with multicore processing.
All cores are being used.

Best wishes,
Hajk
