### ISSUE TITLE
lots of CDS lost during orthology inference

### ISSUE THREAD

**Issue by siriusb-nox** [HajkD/orthologr#8]
Hi there,

I am trying to compute dNdS values between the entire CDS of two genomes (from two subspecies). Each CDS file contain about 30000 sequences. When I do the analysis (using the "dNdS" function), the total amount of CDS pairs that get analyze though is dramatically reduced to nearly 5 to 6 thousand.  I have read the manual, but I am not entirely sure whether there is a way inside the dNdS function to use customized settings for the blast search (e.g. reducing alignment length, etc). I would be very grateful if you could perhaps indicate to me a way to change specific blast settings or filters inside the dNdS function to increase the number of CDS I get analysed.

Many thanks!

Oscar

**Comment by HajkD** [comment]
Hi Oscar,

Many thanks for contacting me and this is an excellent question which I forgot to document properly.

In the `read.cds()` function which I use to import the CDS sequences I internally test whether or not a sequence contains only base triplets by checking `mod(nchar(seq)) == 3` . 

I noticed a while ago that not all sequences in fasta files that are supposed to contain CDS can be divided by 3 and thus might cause problems when translating them due to frameshifts etc.

To be on the conservative side I decided to remove such sequences before translating them and using them for dNdS inference because codon alignments can also be messed up when CDS cannot be divided by 3 and thus don't contain only codons.

What I can do however is to add an argument to omit this check and retain all sequences.
I will also make sure to document this point much better now.

I will write you again as soon as I have this new functionality implemented.

You will then be able to re-run the analysis with all sequences.

I hope this helps :)

Many thanks and best wishes,
Hajk

**Comment by HajkD** [comment]
Hi Oscar,

I now added a new argument `delete_corrupt_cds` to the function `dNdS()`, `read.cds()`, `cds2aa()`, `blast()`, `set_blast()`, `blast_best()`, and `blast_rec` to remove corrupted input coding sequences prior to any dN/dS inference (`delete_corrupt_cds` is now set to `TRUE` as default).

Independent whether or not `delete_corrupt_cds` is set to `TRUE` or `FALSE` the `read.cds()` function which is also used in `dNdS()` will now automatically notify users when their input CDS `fasta` file contains sequences that cannot be divided by 3  (`mod(nchar(seq)) != 3`). In that case, a seperate `fasta` is generated by `read.cds()` storing all corrupted coding sequences so that they
can be validated and studied in detail.

Here is a small example of how you can catch and study corrupted coding sequences:

```r
install.packages("biomartr") # install package biomartr to download coding sequences
# download coding sequences for all protein coding genes of Arabidopsis thaliana from NCBI RefSeq
Ath_cds <- biomartr::getCDS(organism = "Arabidopsis thaliana")
# import downloaded coding sequences using the read.cds() function from orthologr
test_ath <- orthologr::read.cds(Ath_cds, "fasta")
```

Now a warning message is generated when CDS files contain corrupted sequences.

```
There seem to be 35 coding sequences in your input dataset which cannot be properly divided in base triplets, because their sequence length cannot be divided by 3.
A fasta file storing all corrupted coding sequences for inspection was generated and stored at 'Arabidopsis_thaliana_cds_from_genomic_refseq.fna.gz_corrupted_cds_seqs.fasta'.
You chose option 'delete_corrupt_cds = TRUE', thus corrupted coding sequences were removed. If after consulting the file 'Arabidopsis_thaliana_cds_from_genomic_refseq.fna.gz_corrupted_cds_seqs.fasta' you still wish to retain all coding sequences please specify the argument 'delete_corrupt_cds = FALSE'.
```
As you can see, the official CDS annotation file for `A. thaliana` from NCBI RefSeq contains 35 corrupted sequences that cannot be divided by 3 and thus cannot be divided into base triplets.

Since `orthologr::read.cds()` now generated the file `Arabidopsis_thaliana_cds_from_genomic_refseq.fna.gz_corrupted_cds_seqs.fasta` we can study such sequences by importing the corresponding file as following:

```r
# import corupted CDS file
corrupted_seqs <- biomartr::read_cds("Arabidopsis_thaliana_cds_from_genomic_refseq.fna.gz_corrupted_cds_seqs.fasta")
# prove that corrupted sequences truly cannot be divided by 3
nchar(corrupted_seqs) %% 3
```

```
[1] 1 1 2 2 2 2 1 2 2 2 1 2 2 2 1 1 1 1 2 1 2 2 2 2 1 2 2 1 2 2 1 1 2
[34] 1 2
```

## Using `delete_corrupt_cds` in `dNdS()`

Users can now seletect in `dNdS()` whether or not corrupted CDS shall be removed:

```r
dNdS(query_file      = system.file('seqs/ortho_thal_cds.fasta', package = 'orthologr'),
     subject_file    = system.file('seqs/ortho_lyra_cds.fasta', package = 'orthologr'),
     delete_corrupt_cds = TRUE, # coding sequences that cannot be divided by 3 (triplets) will be removed
     ortho_detection = "RBH", # perform BLAST best reciprocal hit orthology inference
     aa_aln_type     = "pairwise", # perform pairwise global alignments of AA seqs 
     aa_aln_tool     = "NW", # using Needleman-Wunsch
     codon_aln_tool  = "pal2nal", # perform codon alignments using the tool Pal2Nal
     dnds_est.method = "Comeron", # use Comeron's method for dN/dS inference
     comp_cores      = 1 )
``` 

I hope this helps and will make it easier for you to understand why some CDS are corrupted.

Once more many thanks for asking this great question.

Best wishes,
Hajk
